% When submitting your files, remember to upload this *tex file, the pdf generated with it, the *bib file (if bibliography is not within the *tex) and all the figures.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% Version 3.3 Generated 2016/11/10 %%%
%%% You will need to have the following packages installed: datetime, fmtcount, etoolbox, fcprefix, which are normally inlcuded in WinEdt. %%%
%%% In http://www.ctan.org/ you can find the packages and how to install them, if necessary. %%%
%%%  NB logo1.jpg is required in the path in order to correctly compile front
%%%  page header %%%

%% Bias in longitudinal cohort studies
%% Author: Denis Haine
%% Research topic
%% Date: 20170818
%% To compile:
%%  Rscript -e "library(knitr); knit('file.Rnw')"
%%  pdflatex file.tex
%%  bibtex file
%%  pdflatex file.tex
%%  pdflatex file.tex
%%
%% bibexport -o extracted.bib myarticle.aux
%%===============================================================

\documentclass[utf8]{frontiersSCNS} % for Science, Engineering and Humanities and Social Sciences articles
%\documentclass[utf8]{frontiersHLTH} % for Health articles
%\documentclass[utf8]{frontiersFPHY} % for Physics and Applied Mathematics and Statistics articles
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

%\setcitestyle{square} % for Physics and Applied Mathematics and Statistics articles
\usepackage{url,hyperref,lineno,microtype,subcaption}
\usepackage[onehalfspacing]{setspace}

\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{relsize}
\usepackage{amssymb}  % for math symbols
\usepackage{mathtools}  % mathtools builds on and extends amsmath package
\usepackage{moreverb}
\usepackage{xspace}
\usepackage{booktabs}
\usepackage{xfrac}
\usepackage{cleveref}
\usepackage{paralist}  % for in-line list
\usepackage{siunitx}
\usepackage[autolanguage]{numprint}
\usepackage[super]{nth}  % to generate English ordinal numbers

\newcommand{\code}[1]{\texttt{\smaller #1}}
\newcommand{\R}{{\normalfont\textsf{R}}{}}


\linenumbers


% Leave a blank line between paragraphs instead of using \\


\def\keyFont{\fontsize{8}{11}\helveticabold }
\def\firstAuthorLast{Haine {et~al.}} %use et al only if is more than 1 author
\def\Authors{Denis Haine\,$^{1,3,*}$, Ian Dohoo\,$^{2,3}$ and Simon Dufour\,$^{1,3}$}
% Affiliations should be keyed to the author's name with superscript numbers and be listed as follows: Laboratory, Institute, Department, Organization, City, State abbreviation (USA, Canada, Australia), and Country (without detailed address information such as city zip codes or street names).
% If one of the authors has a change of address, list the new address below the correspondence details using a superscript symbol and use the same symbol to indicate the author in the author list.
\def\Address{$^{1}$Faculté de médecine vétérinaire, Université de Montréal, St-Hyacinthe, QC, Canada \\
$^{2}$Centre for Veterinary Epidemiological Research, Atlantic Veterinary
College, University of Prince Edward Island, Charlottetown, PE, Canada \\
$^{3}$Canadian Bovine Mastitis and Milk Quality Research Network, St-Hyacinthe,
QC, Canada}
% The Corresponding Author should be marked with an asterisk
% Provide the exact contact address (this time including street name and city zip code) and email of the corresponding author
\def\corrAuthor{Simon Dufour}

\def\corrEmail{simon.dufour@umontreal.ca}


\graphicspath{{graphics/pdf/}}

\newcommand{\rmm}{3.4.3}

\begin{document}
\onecolumn
\firstpage{1}

\title[Bias in Cohort Studies]{Selection and Misclassification Biases in
  Longitudinal Studies} 

\author[\firstAuthorLast ]{\Authors} %This field will be automatically populated
\address{} %This field will be automatically populated
\correspondance{} %This field will be automatically populated

\extraAuth{}% If there are more than 1 corresponding author, comment this line and uncomment the next one.
%\extraAuth{corresponding Author2 \\ Laboratory X2, Institute X2, Department X2, Organization X2, Street X2, City X2 , State XX2 (only USA, Canada and Australia), Zip Code2, X2 Country X2, email2@uni2.edu}


\maketitle


\begin{abstract}

%%% Leave the Abstract empty if your article does not require one, please see the Summary Table for full details.
  \section{}
\input{abstract.tex}

% For full guidelines regarding your manuscript please refer to \href{http://www.frontiersin.org/about/AuthorGuidelines}{Author Guidelines}.

\tiny
 \keyFont{ \section{Keywords:} bias (epidemiology), longitudinal study,
   selection bias, misclassification, epidemiologic methods} %All article types: you may provide up to 8 keywords; at least 5 are mandatory.
\end{abstract}

<<setup1,echo=FALSE>>=
# For more publication-ready graphics
spar <- function(mar = if(!axes)
                 c(2.25 + bot - .45*multi, 2 + left, .5 + top + .25*multi,
                   .5+rt) else
                 c(3.25 + bot - .45*multi, 3.5 + left, .5 + top + .25*multi,
                   .5+rt),
                 lwd = if(multi)1 else 1.75,
                 mgp = if(!axes) mgp = c(.75, .1, 0) else
                 if(multi) c(1.5, .365, 0) else c(2.4 - .4, 0.475, 0),
                 tcl = if(multi)-0.25 else -0.4, xpd = FALSE,
                 bot = 0, left = 0, top = 0, rt = 0, ps = if(multi) 14 else 10,
                 mfrow = NULL, axes = TRUE, cex.lab = 1.25, cex.axis = 1.15,
                 ...) {
  multi <- length(mfrow) > 0
  par(mar = mar, lwd = lwd, mgp = mgp, tcl = tcl, ps = ps, xpd = xpd,
      cex.lab = cex.lab, cex.axis = cex.axis, ...)
  if(multi) par(mfrow = mfrow)
}

knitrSet <- function(basename=NULL, w=3.9, h=2.925,
                     fig.align='center', fig.show='hold', fig.pos='htbp',
                     fig.lp=paste('fig', basename, sep=':'), dev=c('pdf','jpeg'),
                     tidy=FALSE, error=FALSE,
                     messages=c('messages.txt', 'console'),
                     width=65, decinline=5, size=NULL,cache=FALSE,
                     echo=TRUE,results='markup') {
  messages <- match.arg(messages)
  ## Specify e.g. dev=c('pdf','png') or dev=c('pdf','postscript')
  ## to produce two graphics files for each plot
  ## But: dev='CairoPNG' is preferred for png
  if(length(basename)) basename <- paste(basename, '-', sep='')

  options(width=width)
  ## fills Sweavel boxes when font size is \small and svmono.cls (61)
  ## is in effect (use 65 without svmono)

  render_listings()
  if(messages != 'console') {
	unlink(messages) # Start fresh with each run
	hook_log = function(x, options) cat(x, file=messages, append=TRUE)
	knit_hooks$set(warning = hook_log, message = hook_log)
  }
  else opts_chunk$set(message=FALSE, warning=FALSE)
  if(length(size)) opts_chunk$set(size = size)

  if(length(decinline)) {
    rnd <- function(x, dec) if(!is.numeric(x)) x else round(x, dec)
    formals(rnd) <- list(x=NULL, dec=decinline)
    knit_hooks$set(inline = rnd)
  }
  knit_hooks$set(par=function(before, options, envir)
                 if(before && options$fig.show != 'none') {
                   p <- c('bty','mfrow','ps','bot','top','left','rt','lwd',
                          'mgp','tcl', 'axes','xpd')
                   pars <- opts_current$get(p)
                   pars <- pars[!is.na(names(pars))]
                   ## knitr 1.6 started returning NULLs for unspecified pars
                   i <- sapply(pars, function(x) length(x) > 0)
                   if(any(i)) do.call('spar', pars[i]) else spar()
#                   if(length(pars)) do.call('spar', pars) else spar()
                 })
  opts_knit$set(
    aliases=c(h='fig.height', w='fig.width', cap='fig.cap', scap='fig.scap'))
    #eval.after = c('fig.cap','fig.scap'),
    #error=error)  #, keep.source=keep.source (TRUE))
  opts_chunk$set(fig.path=paste('graphics/pdf/', basename, sep=''),
                 fig.align=fig.align, w=w, h=h,
                 fig.show=fig.show, fig.lp=fig.lp, fig.pos=fig.pos,
                 dev=dev, par=TRUE, tidy=tidy, out.width=NULL, cache=cache,
                 echo=echo, results=results, error=error)
  hook_chunk = knit_hooks$get('chunk')
  ## centering will not allow too-wide figures to go into left margin
  knit_hooks$set(chunk = function(x, options) { 
    res = hook_chunk(x, options) 
    if (options$fig.align != 'center') return(res) 
    gsub('\\{\\\\centering (\\\\includegraphics.+)\n\n\\}', 
         '\\\\centerline{\\1}', res) 
  })
}
## see http://yihui.name/knitr/options#package_options

## Use caption package options to control caption font size

## Function to layout multiple lattice graphs into a 2x2 matrix
pmlattice <- function(..., nc=2) {
  w <- list(...)
  if(!inherits(w[[1]], 'trellis')) w <- w[[1]]
  n <- length(w)
  nr <- ceiling(n / nc)
  row <- 1
  col <- 0
  for(i in 1 : n) {
    col <- col + 1
    if(col > nc) {
      col <- 1
      row <- row + 1
    }
    print(w[[i]], more=i < n, split=c(col, row,  nc, nr))
  }
}
@

<<setup2,echo=FALSE,results='asis'>>=
echo <- TRUE # includecode in report
# echo <- FALSE # exclude code in report
cat('%------------------\n')
cat(sprintf('\\def\\inclcode{%s}\n', 1 * echo))
knitrSet()
knitrSet('master', echo = echo)
@

<<packages-load,results='hide',echo=FALSE>>=
library(data.table)
library(reshape2)
library(stringr)
library(ggplot2)
library(directlabels)
library(RColorBrewer)
rsession <- sessionInfo()
rmm <- paste(rsession$R.version$major, rsession$R.version$minor, sep = ".")
@ 

<<data-load20_10,results='hide',echo=FALSE>>=
load("../data/R_star_20_10.RData")
@

<<bias20_10,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_10 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_10)
ids <- str_sub(ids, start = 7)
total_bias_R20_10 <- cbind(total_bias_R20_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_10$Pr <- 20
total_bias_R20_10$Inc <- 0.1

selection_bias_R20_10 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_10)
ids <- str_sub(ids, start = 7)
selection_bias_R20_10 <- cbind(selection_bias_R20_10,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_10 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_10 <- cbind(misclassification_bias_R20_10,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_10)
ids <- str_sub(ids, start = 7)
total_bias_RR20_10 <- cbind(total_bias_RR20_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_10$Pr <- 20
total_bias_RR20_10$Inc <- 0.1

selection_bias_RR20_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_10 <- cbind(selection_bias_RR20_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_10 <- cbind(misclassification_bias_RR20_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_10,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(0.1, .14, .18, .22, .25)) +
    annotate("text", x = 1, y = 1, label = "0.1", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0, 0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(0.1, seq(.12, .18, .02))) +
    annotate("text", x = 1, y = 1, label = "0.1", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0, 0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(seq(0.08, .12, .02), .15, .2, .25)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@

<<RR_row20_10,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2, 2.4)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects",
                                  colour = 'darkgreen'))

rr <- ggplot(selection_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(1.7, 2.6, .3)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects",
                                  colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(1.4, 2.3, .3)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") + 
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects",
                                colour = 'darkgreen'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load20_01,results='hide',echo=FALSE>>=
load("../data/R_star_20_01.RData")
@

<<bias20_01,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_01 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_01)
ids <- str_sub(ids, start = 7)
total_bias_R20_01 <- cbind(total_bias_R20_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_01$Pr <- 20
total_bias_R20_01$Inc <- 0.01

selection_bias_R20_01 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_01)
ids <- str_sub(ids, start = 7)
selection_bias_R20_01<- cbind(selection_bias_R20_01,
                              colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_01 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_01 <- cbind(misclassification_bias_R20_01,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_01)
ids <- str_sub(ids, start = 7)
total_bias_RR20_01 <- cbind(total_bias_RR20_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_01$Pr <- 20
total_bias_RR20_01$Inc <- 0.01

selection_bias_RR20_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_01 <- cbind(selection_bias_RR20_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_01 <- cbind(misclassification_bias_RR20_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_01,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +

    geom_contour(aes(colour = ..level..), breaks = c(.02, seq(.05, .2, .05), .24)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Prevalence 20%", subtitle = "True incidence rate = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Selection bias", subtitle = "True incidence rate = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(.02, .2, .03)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "True incidence rate = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@

<<RR_row20_01,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Prevalence 20%", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(selection_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.4, 1.6, 2, 2.4)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Selection bias", subtitle = "Disease incidence = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.6)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
<<data-load20_05,results='hide',echo=FALSE>>=
load("../data/R_star_20_05.RData")
@

<<bias20_05,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_05 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_05)
ids <- str_sub(ids, start = 7)
total_bias_R20_05 <- cbind(total_bias_R20_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_05$Pr <- 20
total_bias_R20_05$Inc <- 0.05

selection_bias_R20_05 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_05)
ids <- str_sub(ids, start = 7)
selection_bias_R20_05<- cbind(selection_bias_R20_05,
                              colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_05 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_05 <- cbind(misclassification_bias_R20_05,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_05)
ids <- str_sub(ids, start = 7)
total_bias_RR20_05 <- cbind(total_bias_RR20_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_05$Pr <- 20
total_bias_RR20_05$Inc <- 0.05

selection_bias_RR20_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_05 <- cbind(selection_bias_RR20_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_05 <- cbind(misclassification_bias_RR20_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_05,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.06, seq(.1, .2, .05), .26)) +
    annotate("text", x = 1, y = 1, label = "0.05", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(y = "Specificity", subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.04, .05, seq(.1, .26, .04))) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@ 

<<RR_row20_05,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2, 2.5, 3)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", color = 'darkgreen'))

rr <- ggplot(selection_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(seq(1.6, 2.8, .4), 3)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(seq(1.2, 2, .4), 3)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load5_01,results='hide',echo=FALSE>>=
load("../data/R_star_05_01.RData")
@

<<bias05_01,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_01 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_01)
ids <- str_sub(ids, start = 7)
total_bias_R05_01 <- cbind(total_bias_R05_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_01$Pr <- 5
total_bias_R05_01$Inc <- 0.01

selection_bias_R05_01 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_01)
ids <- str_sub(ids, start = 7)
selection_bias_R05_01 <- cbind(selection_bias_R05_01,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_01 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_01 <- cbind(misclassification_bias_R05_01,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_01)
ids <- str_sub(ids, start = 7)
total_bias_RR05_01 <- cbind(total_bias_RR05_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_01$Pr <- 5
total_bias_RR05_01$Inc <- 0.01

selection_bias_RR05_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_01 <- cbind(selection_bias_RR05_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_01 <- cbind(misclassification_bias_RR05_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_01,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.02, .05, .1, .15, .2)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Prevalence 5%", subtitle = "True incidence rate = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Selection bias", subtitle = "True incidence rate = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(.02, .2, .03)) +
    annotate("text", x = 1, y = 1, label = "0.01", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "True incidence rate = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@

<<RR_row05_01,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2, 2.5)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 5%", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(selection_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Selection bias", subtitle = "Disease incidence = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 2)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load05_05,results='hide',echo=FALSE>>=
load("../data/R_star_05_05.RData")
@

<<bias05_05,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_05 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_05)
ids <- str_sub(ids, start = 7)
total_bias_R05_05 <- cbind(total_bias_R05_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_05$Pr <- 5
total_bias_R05_05$Inc <- 0.05

selection_bias_R05_05 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_05)
ids <- str_sub(ids, start = 7)
selection_bias_R05_05 <- cbind(selection_bias_R05_05,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_05 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_05 <- cbind(misclassification_bias_R05_05,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_05)
ids <- str_sub(ids, start = 7)
total_bias_RR05_05 <- cbind(total_bias_RR05_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_05$Pr <- 5
total_bias_RR05_05$Inc <- 0.05

selection_bias_RR05_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_05 <- cbind(selection_bias_RR05_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_05 <- cbind(misclassification_bias_RR05_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_05,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.06, .1, .15, .2, .24)) +
    annotate("text", x = 1, y = 1, label = "0.05", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(.05, .065, .005)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "True incidence rate = 0.05", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.04, seq(.05, .2, .05))) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@

<<RR_row05_05,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2, 2.4, 2.8)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(selection_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(2.2, 2.3, 2.4, 2.6, 2.8, 2.9)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.4, 1.6, 2)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load05_10,results='hide',echo=FALSE>>=
load("../data/R_star_05_10.RData")
@

<<bias05_10,echo=FALSE,results='hide'>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_10 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_10)
ids <- str_sub(ids, start = 7)
total_bias_R05_10 <- cbind(total_bias_R05_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_10$Pr <- 5
total_bias_R05_10$Inc <- 0.1

selection_bias_R05_10 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_10)
ids <- str_sub(ids, start = 7)
selection_bias_R05_10 <- cbind(selection_bias_R05_10,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_10 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_10 <- cbind(misclassification_bias_R05_10,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_10)
ids <- str_sub(ids, start = 7)
total_bias_RR05_10 <- cbind(total_bias_RR05_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_10$Pr <- 5
total_bias_RR05_10$Inc <- 0.1

selection_bias_RR05_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_10 <- cbind(selection_bias_RR05_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_10 <- cbind(misclassification_bias_RR05_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_10,echo=FALSE,results='hide'>>=
r <- ggplot(total_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(.1, .26, .04)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(selection_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.105, .11, .116)) +
    annotate("text", x = 1, y = 1, label = "0.1", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                               cex = .55, hjust=1, vjust=-.5, box.color = NA,
                               fill = "transparent", "draw.rects", colour = 'darkgreen'))

r <- ggplot(misclassification_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(.08, .1, .14, .18, .22, .26)) +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@

<<RR_row05_10,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.2, 1.5, 2, 2.4)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(selection_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = seq(2.3, 2.7, .1)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkgreen'))

rr <- ggplot(misclassification_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.4, 1.6, 2, 2.4)) +
    annotate("text", x = 1, y = 1, label = "3", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Greens")[9:6]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkgreen'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<incidence_contour,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
library(gtable)
library(grid)
plots1 <- list(r05_01t, r20_01t)
plots2 <- list(r05_05t, r20_05t)
plots3 <- list(r05_10t, r20_10t)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<risk_contour,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(rr05_01t, rr20_01t)
plots2 <- list(rr05_05t, rr20_05t)
plots3 <- list(rr05_10t, rr20_10t)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<incidence5_contourX,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(r05_01s, r05_01m)
plots2 <- list(r05_05s, r05_05m)
plots3 <- list(r05_10s, r05_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<risk5_contourX,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(rr05_01s, rr05_01m)
plots2 <- list(rr05_05s, rr05_05m)
plots3 <- list(rr05_10s, rr05_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<incidence20_contourX,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(r20_01s, r20_01m)
plots2 <- list(r20_05s, r20_05m)
plots3 <- list(r20_10s, r20_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<risk20_contourX,w=8,h=8,echo=FALSE,results='hide', include=FALSE>>=
plots1 <- list(rr20_01s, rr20_01m)
plots2 <- list(rr20_05s, rr20_05m)
plots3 <- list(rr20_10s, rr20_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<dohoo20,echo=FALSE,results='hide'>>=
library(dplyr)
dohoo_01 <- total_bias_R20_01 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05), 0.01))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = c(.925, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 6),
          legend.title = element_text(size = 7),
          legend.margin = margin(c(2, 1, .3, 1)),
          legend.justification = "centre") +
    labs(y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence rate = 0.01. Disease prevalence = 20%") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.01)
dohoo_05 <- total_bias_R20_05 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05)))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = "none") +
    labs(y = "Apparent incidence",
         subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.05)
dohoo_10 <- total_bias_R20_10 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05), 0.1))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = "none") +
    labs(x = "Specificity", y = "Apparent incidence",
         subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.1)
@

<<dohoo20_incidence,w=3.9,h=8.925,echo=FALSE,results='hide', include=FALSE>>=
library(cowplot)
plot_grid(dohoo_01, dohoo_05, dohoo_10,
          nrow = 3,
          align = "hv")
@

<<dohoo5,echo=FALSE,results='hide'>>=
dohoo_01 <- total_bias_R05_01 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05), 0.01))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = c(.925, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 6),
          legend.title = element_text(size = 7),
          legend.margin = margin(c(2, 1, .3, 1)),
          legend.justification = "centre") +
    labs(y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence rate = 0.01. Disease prevalence = 5%") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.01)
dohoo_05 <- total_bias_R05_05 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05)))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = "none") +
    labs(y = "Apparent incidence",
         subtitle = "True incidence rate = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.05)
dohoo_10 <- total_bias_R05_10 %>%
    filter(Se == 0.7 | Se == .99) %>%
    ggplot(aes(x = Sp, y = q50, group = as.factor(Se), colour = as.factor(Se))) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_y_continuous(breaks = sort(c(seq(0, .35, .05), 0.1))) +
    scale_colour_manual(name = "Sensitivity",
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    geom_ribbon(aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          legend.position = "none") +
    labs(x = "Specificity", y = "Apparent incidence",
         subtitle = "True incidence rate = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.1)
@

<<dohoo5_incidence,w=3.9,h=8.925,echo=FALSE,results='hide', include=FALSE>>=
plot_grid(dohoo_01, dohoo_05, dohoo_10,
          nrow = 3,
          align = "hv")
@

<<RR_Se_PrInc,echo=FALSE,results='hide',include=FALSE>>=
total_bias_RR <- rbind(total_bias_RR05_01, total_bias_RR05_05, total_bias_RR05_10,
                       total_bias_RR20_01, total_bias_RR20_05, total_bias_RR20_10)
total_bias_RR$Pr <- as.factor(total_bias_RR$Pr)
total_bias_RR$Inc <- as.factor(total_bias_RR$Inc)
total_bias_RR_Se95 <- subset(total_bias_RR, Se == 0.95)

ggplot(total_bias_RR_Se95, aes(x = Sp, y = q50, shape = Inc, colour = Pr,
                              group = interaction(Inc, Pr))) +
    geom_line(size = .6) +
    geom_point() + 
    scale_colour_manual(name = "Prevalence", labels = c("5%", "20%", "50%"),
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    scale_shape_discrete(name = "Incidence", labels = c("0.01", "0.05", "0.10")) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = seq(1, 3, .2)) +
    annotate("text", x = 1, y = 3, label = "X", size = 2.5) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 8, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_text(size = 7),
          legend.position = c(.35, .65),
          legend.box = "horizontal",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 6),
          legend.title = element_text(size = 7),
          legend.justification = "centre",
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          plot.caption = element_text(colour = "grey41", size = 6)) +
    labs(x = "Specificity of test", y = "Apparent risk ratio",
         title = "Risk ratio total bias as a function of specificity and disease risk",
         caption = "Sensitivity = 0.95; True risk ratio = 3") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))    
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load20_10,results='hide',echo=FALSE>>=
load("../data/R15_star_20_10.RData")
@

<<bias15_20_10,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_10)
ids <- str_sub(ids, start = 7)
total_bias_RR20_10 <- cbind(total_bias_RR20_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_10$Pr <- 20
total_bias_RR20_10$Inc <- 0.1

selection_bias_RR20_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_10 <- cbind(selection_bias_RR20_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_10 <- cbind(misclassification_bias_RR20_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row20_10,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.15, 1.2, 1.25)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_10t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.25, 1.3, 1.35, 1.4)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_10s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.15, 1.25, 1.35)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") + 
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_10m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkorange'))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load20_01,results='hide',echo=FALSE>>=
load("../data/R15_star_20_01.RData")
@

<<bias15_20_01,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_01)
ids <- str_sub(ids, start = 7)
total_bias_RR20_01 <- cbind(total_bias_RR20_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_01$Pr <- 20
total_bias_RR20_01$Inc <- 0.01

selection_bias_RR20_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_01 <- cbind(selection_bias_RR20_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_01 <- cbind(misclassification_bias_RR20_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row20_01,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.05, 1.1)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Prevalence 20%", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_01t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.15, 1.2)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Selection bias", subtitle = "Disease incidence = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_01s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.025, 1.05)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_01m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", color = 'darkorange'))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load20_05,results='hide',echo=FALSE>>=
load("../data/R15_star_20_05.RData")
@

<<bias15_20_05,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_05)
ids <- str_sub(ids, start = 7)
total_bias_RR20_05 <- cbind(total_bias_RR20_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_05$Pr <- 20
total_bias_RR20_05$Inc <- 0.05

selection_bias_RR20_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_05 <- cbind(selection_bias_RR20_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_05 <- cbind(misclassification_bias_RR20_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row20_05,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.05, 1.1, 1.15)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_05t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.15, 1.2, 1.25, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_05s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.2, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_20_05m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkorange'))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load5_01,results='hide',echo=FALSE>>=
load("../data/R15_star_05_01.RData")
@

<<bias15_05_01,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_01)
ids <- str_sub(ids, start = 7)
total_bias_RR05_01 <- cbind(total_bias_RR05_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_01$Pr <- 5
total_bias_RR05_01$Inc <- 0.01

selection_bias_RR05_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_01 <- cbind(selection_bias_RR05_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_01 <- cbind(misclassification_bias_RR05_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row05_01,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.05, 1.1, 1.2, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 5%",
         subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_01t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.15, 1.2, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Selection bias", subtitle = "Disease incidence = 0.01",
         y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_01s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.05, 1.1, 1.15)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(title = "Misclassification bias", subtitle = "Disease incidence = 0.01") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_01m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkorange'))
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load05_05,results='hide',echo=FALSE>>=
load("../data/R15_star_05_05.RData")
@

<<bias15_05_05,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_05)
ids <- str_sub(ids, start = 7)
total_bias_RR05_05 <- cbind(total_bias_RR05_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_05$Pr <- 5
total_bias_RR05_05$Inc <- 0.05

selection_bias_RR05_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_05 <- cbind(selection_bias_RR05_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_05 <- cbind(misclassification_bias_RR05_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row05_05,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.2, 1.25)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_05t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.3, 1.35, 1.4)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_05s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.2, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Disease incidence = 0.05") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_05m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkorange'))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data15-load05_10,results='hide',echo=FALSE>>=
load("../data/R15_star_05_10.RData")
@

<<bias15_05_10,echo=FALSE,results='hide'>>=
## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_10)
ids <- str_sub(ids, start = 7)
total_bias_RR05_10 <- cbind(total_bias_RR05_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_10$Pr <- 5
total_bias_RR05_10$Inc <- 0.1

selection_bias_RR05_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_10 <- cbind(selection_bias_RR05_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_10 <- cbind(misclassification_bias_RR05_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<RR15_row05_10,echo=FALSE,results='hide'>>=
rr <- ggplot(total_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.2, 1.3)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_10t <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(selection_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.4, 1.45)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_10s <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects", colour = 'darkorange'))

rr <- ggplot(misclassification_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..), breaks = c(1.1, 1.2, 1.3, 1.35)) +
    annotate("text", x = 1, y = 1, label = "1.5", size = 2.5, color = "grey48") +
    scale_x_continuous(breaks = seq(0.65, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.75, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.75, 1.025), xlim = c(0.65, 1.025)) +
    scale_colour_gradientn(guide = 'none', colours = brewer.pal(9,"Oranges")[6:9]) +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", subtitle = "Disease incidence = 0.1") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr15_05_10m <- direct.label(rr,
                            list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects", colour = 'darkorange'))
@ 

<<risk15_contour,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(rr15_05_01t, rr15_20_01t)
plots2 <- list(rr15_05_05t, rr15_20_05t)
plots3 <- list(rr15_05_10t, rr15_20_10t)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<risk15_5_contourX,w=8,h=8,echo=FALSE,results='hide',include=FALSE>>=
plots1 <- list(rr15_05_01s, rr15_05_01m)
plots2 <- list(rr15_05_05s, rr15_05_05m)
plots3 <- list(rr15_05_10s, rr15_05_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<risk15_20_contourX,w=8,h=8,echo=FALSE,results='hide', include=FALSE>>=
plots1 <- list(rr15_20_01s, rr15_20_01m)
plots2 <- list(rr15_20_05s, rr15_20_05m)
plots3 <- list(rr15_20_10s, rr15_20_10m)
grobs1 <- lapply(plots1, ggplotGrob)
grobs2 <- lapply(plots2, ggplotGrob)
grobs3 <- lapply(plots3, ggplotGrob)
g1 <- do.call(cbind, c(grobs1, size = "first"))
g2 <- do.call(cbind, c(grobs2, size = "first"))
g3 <- do.call(cbind, c(grobs3, size = "first"))
g4 <- do.call(rbind, c(list(g1, g2, g3), size = "first"))
grid.newpage()
grid.draw(g4)
@

<<RR15_Se_PrInc,echo=FALSE,results='hide',include=FALSE>>=
total_bias_RR <- rbind(total_bias_RR05_01, total_bias_RR05_05, total_bias_RR05_10,
                       total_bias_RR20_01, total_bias_RR20_05, total_bias_RR20_10)
total_bias_RR$Pr <- as.factor(total_bias_RR$Pr)
total_bias_RR$Inc <- as.factor(total_bias_RR$Inc)
total_bias_RR_Se95 <- subset(total_bias_RR, Se == 0.95)

ggplot(total_bias_RR_Se95, aes(x = Sp, y = q50, shape = Inc, colour = Pr,
                              group = interaction(Inc, Pr))) +
    geom_line(size = .6) +
    geom_point() + 
    scale_colour_manual(name = "Prevalence", labels = c("5%", "20%", "50%"),
                        values = c("#999999", "#E69F00", "#56B4E9")) +
    scale_shape_discrete(name = "Incidence", labels = c("0.01", "0.05", "0.10")) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = seq(1, 1.5, .05)) +
    annotate("text", x = 1, y = 1.5, label = "X", size = 2.5) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 8, face = "bold"),
          axis.title.y = element_text(size = 7, angle = 90),
          axis.title.x = element_text(size = 7),
          legend.position = c(.35, .65),
          legend.box = "horizontal",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 6),
          legend.title = element_text(size = 7),
          legend.justification = "centre",
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          plot.caption = element_text(colour = "grey41", size = 6)) +
    labs(x = "Specificity of test", y = "Apparent risk ratio",
         title = "Risk ratio total bias as a function of specificity and disease risk",
         caption = "Sensitivity = 0.95; True risk ratio = 1.5") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))    
@ 

\section{Introduction}

\input{intro.tex}

\section{Material and Methods}

\input{mm.tex}

\section{Results}
\label{sec:results}

\input{results.tex}

\section{Discussion}
\label{sec:discussion}

\input{discussion.tex}

\section*{Conflict of Interest Statement}

The authors declare that the research was conducted in the absence of any
commercial or financial relationships that could be construed as a potential
conflict of interest.

\section*{Author Contributions}

DH conducted the simulations, data analysis, results interpretation, and the
manuscript writing.
ID and SD contributed in interpreting the results and editing the manuscript.
DH, ID, and SD contributed to the planning of the study.

\section*{Funding}

This research was financed by the senior author (SD) Natural Sciences and
Engineering Research Council of Canada Discovery Grant.

% \section*{Acknowledgments}
% This is a short text to acknowledge the contributions of specific colleagues,
% institutions, or agencies that aided the efforts of the authors.

\section*{Supplementary Figures}

\textbf{Figure S1.} Estimated incidence rate as a function of test sensitivity
and specificity, a disease prevalence of 5\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) when using an imperfect test at baseline
(selection bias) or at follow-up (misclassification bias). True incidence rate
is found at the upper right corner (i.e.\ perfect sensitivity and specificity).
\textbf{Figure S2.} Estimated incidence rate as a function of test sensitivity
and specificity, a disease prevalence of 20\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) when using an imperfect test at baseline
(selection bias) or at follow-up (misclassification bias). True incidence rate
is found at the upper right corner (i.e.\ perfect sensitivity and specificity).
\textbf{Figure S3.} Estimated risk ratio as a function of test sensitivity and
specificity, a disease prevalence of 5\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) for an exposure with a true measure of
association corresponding to a risk ratio of \(3.0\) when using an imperfect
test at baseline (selection bias) or at follow-up (misclassification bias). True
risk ratio is found at the upper right corner (i.e.\ perfect sensitivity and
specificity).
\textbf{Figure S4.} Estimated risk ratio as a function of test sensitivity and
specificity, a disease prevalence of 20\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) for an exposure with a true measure of
association corresponding to a risk ratio of \(3.0\) when using an imperfect
test at baseline (selection bias) or at follow-up (misclassification bias). True
risk ratio is found at the upper right corner (i.e.\ perfect sensitivity and
specificity).
\textbf{Figure S5.} Estimated risk ratio as a function of test sensitivity and
specificity, disease prevalence (5 or 20\%), and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) for an exposure with a true measure of
association corresponding to a risk ratio of \(1.5\) when using an imperfect
test both at baseline and follow-up (i.e.\ total bias). True risk ratio is found
at the upper right corner (i.e.\ perfect sensitivity and specificity).
\textbf{Figure S6.} Estimated risk ratio as a function of test specificity and
disease risk, and for a sensitivity of 95\%, when using an imperfect test both
at baseline and follow-up. True risk ratio = \(1.5\).
\textbf{Figure S7.} Estimated risk ratio as a function of test sensitivity and
specificity, a disease prevalence of 5\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) for an exposure with a true measure of
association corresponding to a risk ratio of \(1.5\) when using an imperfect
test at baseline (selection bias) or at follow-up (misclassification bias). True
risk ratio is found at the upper right corner (i.e.\ perfect sensitivity and
specificity).
\textbf{Figure S8.} Estimated risk ratio as a function of test sensitivity and
specificity, a disease prevalence of 20\%, and true disease incidence (0.01,
0.05, 0.1 case/animal-time unit) for an exposure with a true measure of
association corresponding to a risk ratio of \(1.5\) when using an imperfect
test at baseline (selection bias) or at follow-up (misclassification bias). True
risk ratio is found at the upper right corner (i.e.\ perfect sensitivity and
specificity).

\bibliographystyle{frontiersinSCNS_ENG_HUMS} % for Science, Engineering and Humanities and Social Sciences articles, for Humanities and Social Sciences articles please include page numbers in the in-text citations
%\bibliographystyle{frontiersinHLTH&FPHY} % for Health, Physics and Mathematics articles
\bibliography{bias}

%%% Make sure to upload the bib file along with the tex file and PDF
%%% Please see the test.bib file for some examples of references

\section*{Figure captions}

%%% Please be aware that for original research articles we only permit a combined number of 15 figures and tables, one figure with multiple subfigures will count as only one figure.
%%% Use this if adding the figures directly in the mansucript, if so, please remember to also upload the files when submitting your article
%%% There is no need for adding the file termination, as long as you indicate where the file is saved. In the examples below the files (logo1.jpg and logos.jpg) are in the Frontiers LaTeX folder
%%% If using *.tif files convert them to .jpg or .png
%%%  NB logo1.jpg is required in the path in order to correctly compile front page header %%%

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[scale=.95]{master-incidence_contour-1}
    \end{center}
  \caption{Estimated incidence rate (in cases/animal-time unit) as a
function of test sensitivity and specificity, disease prevalence (5 or 20\%),
and true disease incidence (0.01, 0.05, 0.1 case/animal-time unit) when using an
imperfect test both at baseline and follow-up (i.e.\ total bias). True incidence
rate is found at the upper right corner (i.e.\ perfect sensitivity and
specificity).}
  \label{fig:incidence_contour}
\end{figure}

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[scale=.95]{master-risk_contour-1}
    \end{center}
  \caption{Estimated risk ratio as a function of test sensitivity and
    specificity, disease prevalence (5 or 20\%), and true disease incidence
    (0.01, 0.05, 0.1 case/animal-time unit) for an exposure with a true measure
    of association corresponding to a risk ratio of \(3.0\) when using an
    imperfect test both at baseline and follow-up (i.e.\ total bias). True risk
    ratio is found at the upper right corner (i.e.\ perfect sensitivity and
    specificity).}
  \label{fig:incidence_risk}
\end{figure}

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[scale=.95]{master-dohoo5_incidence-1}
    \end{center}
  \caption{Apparent incidence resulting from total bias, as a function of
    specificity. Disease prevalence = 5\%. Solid line: median value; dotted
    lines: first and third quartiles.}
  \label{fig:apparent_incidence_5}
\end{figure}

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[scale=.95]{master-dohoo20_incidence-1}
    \end{center}
  \caption{Apparent incidence resulting from total bias, as a function of
    specificity. Disease prevalence = 20\%. Solid line: median value; dotted
    lines: first and third quartiles.}
  \label{fig:apparent_incidence_20}
\end{figure}

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[scale=.95]{master-RR_Se_PrInc-1}
    \end{center}
  \caption{Estimated risk ratio as a function of test specificity and disease
    risk, and for a sensitivity of 95\%, when using an imperfect test both at
    baseline and follow-up. True risk ratio = \(3.0\).}
  \label{fig:apparent_RR}
\end{figure}

%%% If you are submitting a figure with subfigures please combine these into one image file with part labels integrated.
%%% If you don't add the figures in the LaTeX files, please upload them when submitting the article.
%%% Frontiers will add the figures at the end of the provisional pdf automatically
%%% The use of LaTeX coding to draw Diagrams/Figures/Structures should be avoided. They should be external callouts including graphics.

\end{document}

%%% Local Variables:
%%% ispell-local-dictionary: "canadian"
%%% eval: (flyspell-mode 1)
%%% reftex-default-bibliography: ("./bias.bib")
%%% End:
