% When submitting your files, remember to upload this *tex file, the pdf generated with it, the *bib file (if bibliography is not within the *tex) and all the figures.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% Version 3.3 Generated 2016/11/10 %%%
%%% You will need to have the following packages installed: datetime, fmtcount, etoolbox, fcprefix, which are normally inlcuded in WinEdt. %%%
%%% In http://www.ctan.org/ you can find the packages and how to install them, if necessary. %%%
%%%  NB logo1.jpg is required in the path in order to correctly compile front
%%%  page header %%%

%% Bias in longitudinal cohort studies
%% Author: Denis Haine
%% Research topic
%% Date: 20170818
%% To compile:
%%  Rscript -e "library(knitr); knit('file.Rnw')"
%%  pdflatex file.tex
%%  bibtex file
%%  pdflatex file.tex
%%  pdflatex file.tex
%%
%% bibexport -o extracted.bib myarticle.aux
%%===============================================================

\documentclass[utf8]{frontiersSCNS} % for Science, Engineering and Humanities and Social Sciences articles
%\documentclass[utf8]{frontiersHLTH} % for Health articles
%\documentclass[utf8]{frontiersFPHY} % for Physics and Applied Mathematics and Statistics articles
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

%\setcitestyle{square} % for Physics and Applied Mathematics and Statistics articles
\usepackage{url,hyperref,lineno,microtype,subcaption}
\usepackage[onehalfspacing]{setspace}

\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{relsize}
\usepackage{amssymb}  % for math symbols
\usepackage{mathtools}  % mathtools builds on and extends amsmath package
\usepackage{moreverb}
\usepackage{xspace}
\usepackage{booktabs}
\usepackage{xfrac}
\usepackage{paralist}  % for in-line list
\usepackage{siunitx}
\usepackage[autolanguage]{numprint}
\usepackage[super]{nth}  % to generate English ordinal numbers

\newcommand{\code}[1]{\texttt{\smaller #1}}
\newcommand{\R}{{\normalfont\textsf{R}}{}}


\linenumbers


% Leave a blank line between paragraphs instead of using \\


\def\keyFont{\fontsize{8}{11}\helveticabold }
\def\firstAuthorLast{Haine {et~al.}} %use et al only if is more than 1 author
\def\Authors{Denis Haine\,$^{1,3,*}$, Ian Dohoo\,$^{2,3}$ and Simon Dufour\,$^{1,3}$}
% Affiliations should be keyed to the author's name with superscript numbers and be listed as follows: Laboratory, Institute, Department, Organization, City, State abbreviation (USA, Canada, Australia), and Country (without detailed address information such as city zip codes or street names).
% If one of the authors has a change of address, list the new address below the correspondence details using a superscript symbol and use the same symbol to indicate the author in the author list.
\def\Address{$^{1}$Faculté de médecine vétérinaire, Université de Montréal, St-Hyacinthe, QC, Canada \\
$^{2}$Centre for Veterinary Epidemiological Research, Atlantic Veterinary
College, University of Prince Edward Island, Charlottetown, PE, Canada \\
$^{3}$Canadian Bovine Mastitis and Milk Quality Research Network, St-Hyacinthe,
QC, Canada}
% The Corresponding Author should be marked with an asterisk
% Provide the exact contact address (this time including street name and city zip code) and email of the corresponding author
\def\corrAuthor{Denis Haine}

\def\corrEmail{denis.haine@gmail.com}


\graphicspath{{graphics/pdf/}}


\begin{document}
\onecolumn
\firstpage{1}

\title[Bias in Cohort Studies]{Selection and Misclassification Biases in
  Longitudinal Studies} 

\author[\firstAuthorLast ]{\Authors} %This field will be automatically populated
\address{} %This field will be automatically populated
\correspondance{} %This field will be automatically populated

\extraAuth{}% If there are more than 1 corresponding author, comment this line and uncomment the next one.
%\extraAuth{corresponding Author2 \\ Laboratory X2, Institute X2, Department X2, Organization X2, Street X2, City X2 , State XX2 (only USA, Canada and Australia), Zip Code2, X2 Country X2, email2@uni2.edu}


\maketitle


\begin{abstract}

%%% Leave the Abstract empty if your article does not require one, please see the Summary Table for full details.
  \section{}
  Using imperfect tests may lead to biased estimates of disease frequency and
  measures of association.
  Many studies have looked into the effect of misclassification on statistical
  inferences.
  These evaluations were either within a cross-sectional study framework,
  assessing biased prevalence, or for cohort study designs, evaluating biased
  incidence rate or risk ratio (RR) estimates based on misclassification at one
  of the two time-points (initial assessment or follow-up).
  However, both observations at risk and incident cases can be wrongly
  identified in longitudinal studies, leading to selection and misclassification
  biases, respectively.
  The objective of this paper was to evaluate the relative impact of selection
  and misclassification biases resulting from misclassification, together, on
  measures of incidence and risk ratio.

  To investigate impact on measure of disease frequency, data sets from a
  hypothetical cohort study with two samples collected one month apart were
  simulated and analyzed based on specific test and disease characteristics, for
  a stable population over the follow-up time, and with no elimination of
  disease or clustering of observations.
  Direction and magnitude of bias due to selection, misclassification, and total
  bias was assessed for diagnostic test sensitivity and specificity ranging from
  0.7 to 1.0 and 0.8 to 1.0, respectively, and for specific disease contexts,
  i.e.\ disease prevalences of 5 and 20\%, and disease incidences of 0.01, 0.05,
  and 0.1 cases/animal-month.
  A hypothetical exposure with known strength of association (RR
  \raise.17ex\hbox{$\scriptstyle\sim$}\num{3.0}) was also generated.
  A total of \numprint{1000} cohort studies of \numprint{1000} observations each
  were simulated for these six disease contexts where the same diagnostic test
  was used to identify observations at risk at beginning of the cohort and
  incident cases at its end.
  
  Our results indicated that the departure of the estimates of disease incidence
  and risk ratio from their true value were mainly a function of test
  specificity, and disease prevalence and incidence.
  Imperfect sensitivity to identify individuals at risk and imperfect
  specificity to identify incident cases lead to a mild under-estimation of the
  observed disease incidence.
  The combination of the two biases, at baseline and follow-up, revealed the
  importance of a good to excellent specificity over sensitivity for the
  diagnostic test.
  Small divergence from perfect specificity extended quickly to disease
  incidence over-estimation as true prevalence increased and true incidence
  decreased.
  Selection and misclassification biases of a low prevalent and incident
  disease, diagnosed with close to perfect specificity, were minimal, reflecting
  the importance of choosing a highly specific test to improve unit at risk and
  case identification.
  A highly sensitive test to exclude diseased subjects at baseline was of less
  importance to minimize bias than using a highly specific one.
  For instance, when a test with high specificity cannot be used, one could use
  a less performant test twice at recruitment or for identifying incident cases
  and with a serial interpretation.
  The lost in sensitivity of such an approach would caused little bias, compared
  to the potential gains due to the increased specificity.

  Near perfect diagnostic test attributes were even more important to obtain a
  measure of association close to the true risk ratio, according to specific
  disease characteristics, especially its prevalence.
  Low prevalent and high incident disease lead to minimal bias if disease is
  diagnosed with high sensitivity and close to perfect specificity.
  For more prevalent diseases we observed large risk ratio biases towards the
  null value, even with near perfect diagnosis.
  This bias also got larger as incidence decreased.
  For diseases with moderate to high prevalence (20\%), the biases can be so
  important that a study using a test with a sensitivity or specificity < 0.95
  would have very little power to identify any measure of association with
  exposures.
  Even with prevalence of disease of 5\%, a dramatic loss of power is to be
  expected when imperfect tests are used.

% For full guidelines regarding your manuscript please refer to \href{http://www.frontiersin.org/about/AuthorGuidelines}{Author Guidelines}.

% As a primary goal, the abstract should render the general significance and conceptual advance of the work clearly accessible to a broad readership. References should not be cited in the abstract. Leave the Abstract empty if your article does not require one, please see \href{http://www.frontiersin.org/about/AuthorGuidelines#SummaryTable}{Summary Table} for details according to article type. 

\tiny
 \keyFont{ \section{Keywords:} bias (epidemiology), longitudinal study,
   selection bias, misclassification} %All article types: you may provide up to 8 keywords; at least 5 are mandatory.
\end{abstract}

<<setup1,echo=FALSE>>=
# For more publication-ready graphics
spar <- function(mar = if(!axes)
                 c(2.25 + bot - .45*multi, 2 + left, .5 + top + .25*multi,
                   .5+rt) else
                 c(3.25 + bot - .45*multi, 3.5 + left, .5 + top + .25*multi,
                   .5+rt),
                 lwd = if(multi)1 else 1.75,
                 mgp = if(!axes) mgp = c(.75, .1, 0) else
                 if(multi) c(1.5, .365, 0) else c(2.4 - .4, 0.475, 0),
                 tcl = if(multi)-0.25 else -0.4, xpd = FALSE,
                 bot = 0, left = 0, top = 0, rt = 0, ps = if(multi) 14 else 10,
                 mfrow = NULL, axes = TRUE, cex.lab = 1.25, cex.axis = 1.15,
                 ...) {
  multi <- length(mfrow) > 0
  par(mar = mar, lwd = lwd, mgp = mgp, tcl = tcl, ps = ps, xpd = xpd,
      cex.lab = cex.lab, cex.axis = cex.axis, ...)
  if(multi) par(mfrow = mfrow)
}

knitrSet <- function(basename=NULL, w=3.9, h=2.925,
                     fig.align='center', fig.show='hold', fig.pos='htbp',
                     fig.lp=paste('fig', basename, sep=':'), dev='pdf',
                     tidy=FALSE, error=FALSE,
                     messages=c('messages.txt', 'console'),
                     width=65, decinline=5, size=NULL,cache=FALSE,
                     echo=TRUE,results='markup') {
  messages <- match.arg(messages)
  ## Specify e.g. dev=c('pdf','png') or dev=c('pdf','postscript')
  ## to produce two graphics files for each plot
  ## But: dev='CairoPNG' is preferred for png
  if(length(basename)) basename <- paste(basename, '-', sep='')

  options(width=width)
  ## fills Sweavel boxes when font size is \small and svmono.cls (61)
  ## is in effect (use 65 without svmono)

  render_listings()
  if(messages != 'console') {
	unlink(messages) # Start fresh with each run
	hook_log = function(x, options) cat(x, file=messages, append=TRUE)
	knit_hooks$set(warning = hook_log, message = hook_log)
  }
  else opts_chunk$set(message=FALSE, warning=FALSE)
  if(length(size)) opts_chunk$set(size = size)

  if(length(decinline)) {
    rnd <- function(x, dec) if(!is.numeric(x)) x else round(x, dec)
    formals(rnd) <- list(x=NULL, dec=decinline)
    knit_hooks$set(inline = rnd)
  }
  knit_hooks$set(par=function(before, options, envir)
                 if(before && options$fig.show != 'none') {
                   p <- c('bty','mfrow','ps','bot','top','left','rt','lwd',
                          'mgp','tcl', 'axes','xpd')
                   pars <- opts_current$get(p)
                   pars <- pars[!is.na(names(pars))]
                   ## knitr 1.6 started returning NULLs for unspecified pars
                   i <- sapply(pars, function(x) length(x) > 0)
                   if(any(i)) do.call('spar', pars[i]) else spar()
#                   if(length(pars)) do.call('spar', pars) else spar()
                 })
  opts_knit$set(
    aliases=c(h='fig.height', w='fig.width', cap='fig.cap', scap='fig.scap'))
    #eval.after = c('fig.cap','fig.scap'),
    #error=error)  #, keep.source=keep.source (TRUE))
  opts_chunk$set(fig.path=paste('graphics/pdf/', basename, sep=''),
                 fig.align=fig.align, w=w, h=h,
                 fig.show=fig.show, fig.lp=fig.lp, fig.pos=fig.pos,
                 dev=dev, par=TRUE, tidy=tidy, out.width=NULL, cache=cache,
                 echo=echo, results=results, error=error)
  hook_chunk = knit_hooks$get('chunk')
  ## centering will not allow too-wide figures to go into left margin
  knit_hooks$set(chunk = function(x, options) { 
    res = hook_chunk(x, options) 
    if (options$fig.align != 'center') return(res) 
    gsub('\\{\\\\centering (\\\\includegraphics.+)\n\n\\}', 
         '\\\\centerline{\\1}', res) 
  })
}
## see http://yihui.name/knitr/options#package_options

## Use caption package options to control caption font size

## Function to layout multiple lattice graphs into a 2x2 matrix
pmlattice <- function(..., nc=2) {
  w <- list(...)
  if(!inherits(w[[1]], 'trellis')) w <- w[[1]]
  n <- length(w)
  nr <- ceiling(n / nc)
  row <- 1
  col <- 0
  for(i in 1 : n) {
    col <- col + 1
    if(col > nc) {
      col <- 1
      row <- row + 1
    }
    print(w[[i]], more=i < n, split=c(col, row,  nc, nr))
  }
}
@

<<setup2,echo=FALSE,results='asis'>>=
echo <- TRUE # includecode in report
# echo <- FALSE # exclude code in report
cat('%------------------\n')
cat(sprintf('\\def\\inclcode{%s}\n', 1 * echo))
knitrSet()
knitrSet('master', echo = echo)
@

<<packages-load,results='hide',echo=FALSE,eval=FALSE>>=
library(data.table)
library(reshape2)
library(stringr)
library(ggplot2)
library(directlabels)
rsession <- sessionInfo()
rmm <- paste(rsession$R.version$major, rsession$R.version$minor, sep = ".")
@ 

<<data-load20_10,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_20_10.RData")
@

<<bias20_10,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_10 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_10)
ids <- str_sub(ids, start = 7)
total_bias_R20_10 <- cbind(total_bias_R20_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_10$Pr <- 20
total_bias_R20_10$Inc <- 0.1

selection_bias_R20_10 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_10)
ids <- str_sub(ids, start = 7)
selection_bias_R20_10 <- cbind(selection_bias_R20_10,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_10 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_10 <- cbind(misclassification_bias_R20_10,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_10)
ids <- str_sub(ids, start = 7)
total_bias_RR20_10 <- cbind(total_bias_RR20_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_10$Pr <- 20
total_bias_RR20_10$Inc <- 0.1

selection_bias_RR20_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_10 <- cbind(selection_bias_RR20_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_10 <- cbind(misclassification_bias_RR20_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_10,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_10m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row20_10,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR20_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_10m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load20_01,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_20_01.RData")
@

<<bias20_01,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_01 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_01)
ids <- str_sub(ids, start = 7)
total_bias_R20_01 <- cbind(total_bias_R20_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_01$Pr <- 20
total_bias_R20_01$Inc <- 0.01

selection_bias_R20_01 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_01)
ids <- str_sub(ids, start = 7)
selection_bias_R20_01<- cbind(selection_bias_R20_01,
                              colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_01 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_01 <- cbind(misclassification_bias_R20_01,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_01)
ids <- str_sub(ids, start = 7)
total_bias_RR20_01 <- cbind(total_bias_RR20_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_01$Pr <- 20
total_bias_RR20_01$Inc <- 0.01

selection_bias_RR20_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_01 <- cbind(selection_bias_RR20_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_01 <- cbind(misclassification_bias_RR20_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 20%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_01m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row20_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 20%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR20_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_01m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<data-load20_05,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_20_05.RData")
@

<<bias20_05,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R20_05 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R20_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R20_05)
ids <- str_sub(ids, start = 7)
total_bias_R20_05 <- cbind(total_bias_R20_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R20_05$Pr <- 20
total_bias_R20_05$Inc <- 0.05

selection_bias_R20_05 <- t(apply(fastbound[[2]], 2,
                                 function(x) quantile(x, c(.025, .5, .975),
                                                      na.rm = TRUE)))
colnames(selection_bias_R20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R20_05)
ids <- str_sub(ids, start = 7)
selection_bias_R20_05<- cbind(selection_bias_R20_05,
                              colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R20_05 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R20_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_R20_05 <- cbind(misclassification_bias_R20_05,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR20_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR20_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR20_05)
ids <- str_sub(ids, start = 7)
total_bias_RR20_05 <- cbind(total_bias_RR20_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR20_05$Pr <- 20
total_bias_RR20_05$Inc <- 0.05

selection_bias_RR20_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR20_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR20_05 <- cbind(selection_bias_RR20_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR20_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR20_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR20_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR20_05 <- cbind(misclassification_bias_RR20_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row20_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r20_05m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 

<<RR_row20_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR20_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr20_05m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load5_01,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_05_01.RData")
@

<<bias05_01,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_01 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_01)
ids <- str_sub(ids, start = 7)
total_bias_R05_01 <- cbind(total_bias_R05_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_01$Pr <- 5
total_bias_R05_01$Inc <- 0.01

selection_bias_R05_01 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_01)
ids <- str_sub(ids, start = 7)
selection_bias_R05_01 <- cbind(selection_bias_R05_01,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_01 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_01 <- cbind(misclassification_bias_R05_01,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_01)
ids <- str_sub(ids, start = 7)
total_bias_RR05_01 <- cbind(total_bias_RR05_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_01$Pr <- 5
total_bias_RR05_01$Inc <- 0.01

selection_bias_RR05_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_01 <- cbind(selection_bias_RR05_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_01 <- cbind(misclassification_bias_RR05_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 5%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_01m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row05_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 5%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR05_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_01m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load05_05,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_05_05.RData")
@

<<bias05_05,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_05 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_05)
ids <- str_sub(ids, start = 7)
total_bias_R05_05 <- cbind(total_bias_R05_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_05$Pr <- 5
total_bias_R05_05$Inc <- 0.05

selection_bias_R05_05 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_05)
ids <- str_sub(ids, start = 7)
selection_bias_R05_05 <- cbind(selection_bias_R05_05,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_05 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_05 <- cbind(misclassification_bias_R05_05,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_05)
ids <- str_sub(ids, start = 7)
total_bias_RR05_05 <- cbind(total_bias_RR05_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_05$Pr <- 5
total_bias_RR05_05$Inc <- 0.05

selection_bias_RR05_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_05 <- cbind(selection_bias_RR05_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_05 <- cbind(misclassification_bias_RR05_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_05m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row05_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR05_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_05m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load05_10,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_05_10.RData")
@

<<bias05_10,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R05_10 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R05_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R05_10)
ids <- str_sub(ids, start = 7)
total_bias_R05_10 <- cbind(total_bias_R05_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R05_10$Pr <- 5
total_bias_R05_10$Inc <- 0.1

selection_bias_R05_10 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R05_10)
ids <- str_sub(ids, start = 7)
selection_bias_R05_10 <- cbind(selection_bias_R05_10,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R05_10 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R05_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_R05_10 <- cbind(misclassification_bias_R05_10,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR05_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR05_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR05_10)
ids <- str_sub(ids, start = 7)
total_bias_RR05_10 <- cbind(total_bias_RR05_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR05_10$Pr <- 5
total_bias_RR05_10$Inc <- 0.1

selection_bias_RR05_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR05_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR05_10 <- cbind(selection_bias_RR05_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR05_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR05_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR05_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR05_10 <- cbind(misclassification_bias_RR05_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row05_10,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                               cex = .55, hjust=1, vjust=-.5, box.color = NA,
                               fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r05_10m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row05_10,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR05_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 7),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr05_10m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load50_05,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_50_05.RData")
@

<<totalBias50_05,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R50_05 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R50_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R50_05)
ids <- str_sub(ids, start = 7)
total_bias_R50_05 <- cbind(total_bias_R50_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R50_05$Pr <- 50
total_bias_R50_05$Inc <- 0.05

selection_bias_R50_05 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R50_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R50_05)
ids <- str_sub(ids, start = 7)
selection_bias_R50_05 <- cbind(selection_bias_R50_05,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R50_05 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R50_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R50_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_R50_05 <- cbind(misclassification_bias_R50_05,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR50_05 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR50_05) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR50_05)
ids <- str_sub(ids, start = 7)
total_bias_RR50_05 <- cbind(total_bias_RR50_05, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR50_05$Pr <- 50
total_bias_RR50_05$Inc <- 0.05

selection_bias_RR50_05 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR50_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR50_05)
ids <- str_sub(ids, start = 7)
selection_bias_RR50_05 <- cbind(selection_bias_RR50_05,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR50_05 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR50_05) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR50_05)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR50_05 <- cbind(misclassification_bias_RR50_05,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row50_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_05t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_05s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_05m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row50_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_05t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_05s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR50_05, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_05m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load50_01,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_50_01.RData")
@

<<bias50_01,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R50_01 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R50_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R50_01)
ids <- str_sub(ids, start = 7)
total_bias_R50_01 <- cbind(total_bias_R50_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R50_01$Pr <- 50
total_bias_R50_01$Inc <- 0.01

selection_bias_R50_01 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R50_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R50_01)
ids <- str_sub(ids, start = 7)
selection_bias_R50_01 <- cbind(selection_bias_R50_01,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R50_01 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R50_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R50_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_R50_01 <- cbind(misclassification_bias_R50_01,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR50_01 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR50_01) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR50_01)
ids <- str_sub(ids, start = 7)
total_bias_RR50_01 <- cbind(total_bias_RR50_01, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR50_01$Pr <- 50
total_bias_RR50_01$Inc <- 0.01

selection_bias_RR50_01 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR50_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR50_01)
ids <- str_sub(ids, start = 7)
selection_bias_RR50_01 <- cbind(selection_bias_RR50_01,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR50_01 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR50_01) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR50_01)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR50_01 <- cbind(misclassification_bias_RR50_01,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R_row50_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 6),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(y = "Specificity", title = "Prevalence 50%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_01t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_01s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_01m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@

<<RR_row50_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.title = element_text(size = 8, face = "bold"),
          plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(x = "Sensitivity", title = "Prevalence 50%", subtitle = "Total bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_01t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Selection bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_01s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR50_01, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(plot.subtitle = element_text(size = 7, face = "bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_text(size = 6)) +
    labs(subtitle = "Misclassification bias") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_01m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))
@ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<data-load50_10,results='hide',echo=FALSE,eval=FALSE>>=
load("../data/R_star_50_10.RData")
@

<<bias50_10,echo=FALSE,results='hide',eval=FALSE>>=
## Incidence
fastbind.ith.rows <- function(i) rbindlist(lapply(R_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_R50_10 <- t(apply(fastbound[[1]], 2,
                             function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_R50_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_R50_10)
ids <- str_sub(ids, start = 7)
total_bias_R50_10 <- cbind(total_bias_R50_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_R50_10$Pr <- 50
total_bias_R50_10$Inc <- 0.1

selection_bias_R50_10 <- t(apply(fastbound[[2]], 2,
                          function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(selection_bias_R50_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_R50_10)
ids <- str_sub(ids, start = 7)
selection_bias_R50_10 <- cbind(selection_bias_R50_10,
                               colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_R50_10 <- t(apply(fastbound[[3]], 2,
                                         function(x) quantile(x, c(.025, .5, .975),
                                                              na.rm = TRUE)))
colnames(misclassification_bias_R50_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_R50_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_R50_10 <- cbind(misclassification_bias_R50_10,
                                       colsplit(ids, '_', names = c("Se", "Sp")))

## RR
fastbind.ith.rows <- function(i) rbindlist(lapply(RR_star, "[", i, TRUE))
fastbound <- lapply(1:3, fastbind.ith.rows)
names(fastbound) <- c("Total bias", "Selection bias", "Misclassification bias")

total_bias_RR50_10 <- t(apply(fastbound[[1]], 2,
                              function(x) quantile(x, c(.025, .5, .975), na.rm = TRUE)))
colnames(total_bias_RR50_10) <- c("q2.5", "q50", "q97.5")

ids <- rownames(total_bias_RR50_10)
ids <- str_sub(ids, start = 7)
total_bias_RR50_10 <- cbind(total_bias_RR50_10, colsplit(ids, '_', names = c("Se", "Sp")))
total_bias_RR50_10$Pr <- 50
total_bias_RR50_10$Inc <- 0.1

selection_bias_RR50_10 <- t(apply(fastbound[[2]], 2,
                                  function(x) quantile(x, c(.025, .5, .975),
                                                       na.rm = TRUE)))
colnames(selection_bias_RR50_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(selection_bias_RR50_10)
ids <- str_sub(ids, start = 7)
selection_bias_RR50_10 <- cbind(selection_bias_RR50_10,
                                colsplit(ids, '_', names = c("Se", "Sp")))

misclassification_bias_RR50_10 <- t(apply(fastbound[[3]], 2,
                                          function(x) quantile(x, c(.025, .5, .975),
                                                               na.rm = TRUE)))
colnames(misclassification_bias_RR50_10) <- c("q2.5", "q50", "q97.5")
ids <- rownames(misclassification_bias_RR50_10)
ids <- str_sub(ids, start = 7)
misclassification_bias_RR50_10 <- cbind(misclassification_bias_RR50_10,
                                        colsplit(ids, '_', names = c("Se", "Sp")))
@

<<R50,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
r <- ggplot(total_bias_R50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_10t <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                               cex = .55, hjust=1, vjust=-.5, box.color = NA,
                               fill = "transparent", "draw.rects"))

r <- ggplot(selection_bias_R50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_10s <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                               cex = .55, hjust=1, vjust=-.5, box.color = NA,
                               fill = "transparent", "draw.rects"))

r <- ggplot(misclassification_bias_R50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
r50_10m <- direct.label(r, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                               cex = .55, hjust=1, vjust=-.5, box.color = NA,
                               fill = "transparent", "draw.rects"))

library(cowplot)
plot_grid(r50_01t,r50_01s,r50_01m,r50_05t,r50_05s,r50_05m,r50_10t,r50_10s,r50_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@

<<RR50,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
rr <- ggplot(total_bias_RR50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_text(angle = 90, size = 7),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity", y = "Specificity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_10t <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(selection_bias_RR50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_10s <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                  cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                  fill = "transparent", "draw.rects"))

rr <- ggplot(misclassification_bias_RR50_10, aes(x = Se, y = Sp, z = q50)) +
    geom_contour(aes(colour = ..level..)) +
    scale_x_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .05), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = 'none') +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 6),
          axis.text.y = element_text(size = 5),
          axis.text.x = element_text(size = 5)) +
    labs(x = "Sensitivity") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))
rr50_10m <- direct.label(rr, list("far.from.others.borders", "calc.boxes", "enlarge.box", 
                                cex = .55, hjust=1, vjust=-.5, box.color = NA,
                                fill = "transparent", "draw.rects"))

plot_grid(rr50_01t,rr50_01s,rr50_01m,rr50_05t,rr50_05s,rr50_05m,rr50_10t,rr50_10s,rr50_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@ 

<<R20,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
plot_grid(r20_01t,r20_01s,r20_01m,r20_05t,r20_05s,r20_05m,r20_10t,r20_10s,r20_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@

<<RR20,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
plot_grid(rr20_01t,rr20_01s,rr20_01m,rr20_05t,rr20_05s,rr20_05m,rr20_10t,rr20_10s,rr20_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@

<<R05,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
plot_grid(r05_01t,r05_01s,r05_01m,r05_05t,r05_05s,r05_05m,r05_10t,r05_10s,r05_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@

<<RR05,w=8,h=8,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
plot_grid(rr05_01t,rr05_01s,rr05_01m,rr05_05t,rr05_05s,rr05_05m,rr05_10t,rr05_10s,rr05_10m,
          ncol=3,
          align="hv",
          labels = c("A", "", "", "B", "", "", "C"))
@

<<IncSe_01,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
total_bias_R <- rbind(total_bias_R05_01, total_bias_R05_05, total_bias_R05_10,
                     total_bias_R20_01, total_bias_R20_05, total_bias_R20_10,
                     total_bias_R50_01, total_bias_R50_05, total_bias_R50_10)
total_bias_R$Pr <- as.factor(total_bias_R$Pr)
total_bias_R2 <- subset(total_bias_R, Se + Sp == 1.6)
total_bias_R3 <- subset(total_bias_R, Se + Sp == 1.8)

ggplot(total_bias_R2[total_bias_R2$Inc == 0.01, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.01))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R2[total_bias_R2$Inc == 0.01, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
#    expand_limits(#x=c(0.5, 1),
#        y=c(1, 10)) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.925, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
#          legend.key.width = unit(2, "cm"),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.01; Se + Sp = 1.60") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.01)
@

<<IncSe_05,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
ggplot(total_bias_R2[total_bias_R2$Inc == 0.05, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.05))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R2[total_bias_R2$Inc == 0.05, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.9, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.05; Se + Sp = 1.60") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.05)
@ 

<<IncSe_10,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
ggplot(total_bias_R2[total_bias_R2$Inc == 0.1, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.1))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R2[total_bias_R2$Inc == 0.1, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.9, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.1; Se + Sp = 1.60") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.1)
@

<<IncSe_01_18,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
ggplot(total_bias_R3[total_bias_R3$Inc == 0.01, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.8, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.01))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R3[total_bias_R3$Inc == 0.01, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
#    expand_limits(#x=c(0.5, 1),
#        y=c(1, 10)) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.925, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
#          legend.key.width = unit(2, "cm"),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.01; Se + Sp = 1.80") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.01)
@

<<IncSe_05_18,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
ggplot(total_bias_R3[total_bias_R3$Inc == 0.05, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.8, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.05))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R3[total_bias_R3$Inc == 0.05, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.9, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.05; Se + Sp = 1.80") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.05)
@ 

<<IncSe_10_18,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
ggplot(total_bias_R3[total_bias_R3$Inc == 0.1, ],
       aes(x = Sp, y = q50, group = Pr, colour = Pr)) +
    stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, size = .5) +
    scale_x_continuous(breaks = seq(.8, 1, .05)) + 
    scale_y_continuous(breaks = sort(c(seq(0, .5, .05), 0.1))) +
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    geom_ribbon(data = total_bias_R3[total_bias_R3$Inc == 0.1, ],
                aes(ymin = q2.5, ymax = q97.5),
                linetype = 2, alpha = 0.1, show.legend = FALSE) +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          plot.subtitle = element_text(size = 5, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.9, .8),
          legend.direction = "vertical",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
          legend.margin = margin(c(2, 1, 0.3, 1)),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 8)) +
    labs(x = "Specificity", y = "Apparent incidence",
         title = "Apparent incidence as a function of specificity",
         subtitle = "True incidence = 0.1; Se + Sp = 1.80") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black")) +
    geom_hline(yintercept = 0.1)
@

<<RR_Se_PrInc,echo=FALSE,results='hide',include=FALSE,eval=FALSE>>=
total_bias_RR <- rbind(total_bias_RR05_01, total_bias_RR05_05, total_bias_RR05_10,
                       total_bias_RR20_01, total_bias_RR20_05, total_bias_RR20_10,
                       total_bias_RR50_01, total_bias_RR50_05, total_bias_RR50_10)
total_bias_RR$Pr <- as.factor(total_bias_RR$Pr)
total_bias_RR$Inc <- as.factor(total_bias_RR$Inc)
total_bias_RR_Se9 <- subset(total_bias_RR, Se == 0.9)

ggplot(total_bias_RR_Se9, aes(x = Sp, y = q50, shape = Inc, colour = Pr,
                              group = interaction(Inc, Pr))) +
    geom_line(size = .6) +
    geom_point() + 
    scale_colour_discrete(name = "Prevalence", labels = c("5%", "20%", "50%")) +
    scale_shape_discrete(name = "Incidence", labels = c("0.01", "0.05", "0.10")) +
    scale_x_continuous(breaks = seq(.6, 1, .05)) + 
    scale_y_continuous(breaks = seq(1, 3, .2)) +
    theme_bw() +
    guides(color = guide_legend(override.aes = list(fill = NA))) +
    theme(plot.title = element_text(size = 6, face = "bold"),
          axis.title.y = element_text(size = 5, angle = 90),
          axis.title.x = element_text(size = 5),
          legend.position = c(.35, .65),
          legend.box = "horizontal",
          legend.key = element_rect(colour = "transparent"),
          legend.background = element_rect(linetype = "solid",
                                           colour = "grey42",
                                           size = .2),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5),
          legend.justification = "centre",
          axis.text.y = element_text(size = 4),
          axis.text.x = element_text(size = 4),
          plot.caption = element_text(colour = "grey41", size = 5)) +
    labs(x = "Specificity of test", y = "Apparent relative risk",
         title = "Bias as a function of specificity and disease risk",
         caption = "Sensitivity = 0.90; True relative risk = 3.0") +
    theme(panel.grid.major = element_line(size = .2, color = "grey"),
          axis.line = element_line(size = .15, color = "black"))    
@ 

\newcommand{\rmm}{3.4.1}

% \section{Introduction}

% For Original Research Articles \citep{conference}, Clinical Trial Articles \citep{article}, and Technology Reports \citep{patent}, the introduction should be succinct, with no subheadings \citep{book}. For Case Reports the Introduction should include symptoms at presentation \citep{chapter}, physical exams and lab results \citep{dataset}.

% \bibliographystyle{frontiersinSCNS_ENG_HUMS} % for Science, Engineering and Humanities and Social Sciences articles, for Humanities and Social Sciences articles please include page numbers in the in-text citations
% %\bibliographystyle{frontiersinHLTH&FPHY} % for Health, Physics and Mathematics articles
% \bibliography{bias}

%%% Make sure to upload the bib file along with the tex file and PDF
%%% Please see the test.bib file for some examples of references

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-R05-1}
% \end{center}
% \caption{Incidence---Misclassification bias---Prevalence of 5\% (A = incidence of 0.01; B =
%   incidence of 0.05; C = incidence of 0.1).}\label{fig:p5}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-R20-1}
% \end{center}
% \caption{Incidence---Misclassification bias---Prevalence of 20\% (A = incidence of 0.01; B =
%   incidence of 0.05; C = incidence of 0.1).}\label{fig:p20}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-R50-1}
% \end{center}
% \caption{Incidence---Misclassification bias---Prevalence of 50\% (A = incidence of 0.01; B =
%   incidence of 0.05; C = incidence of 0.1).}\label{fig:p50}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_01-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.60. True incidence is 0.01.}\label{fig:IncSe_01}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_05-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.60. True incidence is 0.05.}\label{fig:IncSe_05}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_10-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.60. True incidence is 0.1.}\label{fig:IncSe_1}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_01_18-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.80. True incidence is 0.01.}\label{fig:IncSe_01_18}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_05_18-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.80. True incidence is 0.05.}\label{fig:IncSe_05_18}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-IncSe_10_18-1}
% \end{center}
% \caption{Apparent incidence and 95\% confidence interval as a function of
%   specificity, for various prevalences, and with a combined sensitivity and
%   specificity of 1.80. True incidence is 0.1.}\label{fig:IncSe_1_18}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-RR05-1}
% \end{center}
% \caption{Relative risk---Misclassification bias---Prevalence of 5\% (A =
%   incidence of 0.01; B = incidence of 0.05; C = incidence of 0.1).}\label{fig:RR05}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-RR20-1}
% \end{center}
% \caption{Relative risk---Misclassification bias---Prevalence of 20\% (A =
%   incidence of 0.01; B = incidence of 0.05; C = incidence of 0.1).}\label{fig:RR20}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-RR50-1}
% \end{center}
% \caption{Relative risk---Misclassification bias---Prevalence of 50\% (A =
%   incidence of 0.01; B = incidence of 0.05; C = incidence of 0.1).}\label{fig:RR50}
% \end{figure}

% \begin{figure}[h!]
% \begin{center}
% \includegraphics[width=\textwidth]{master-RR_Se_PrInc-1}
% \end{center}
% \caption{Bias to relative risk as a function of specificity and disease
%   risk.}\label{fig:RR_PrInc}
% \end{figure}

\end{document}

%%% Local Variables:
%%% ispell-local-dictionary: "canadian"
%%% eval: (flyspell-mode 1)
%%% reftex-default-bibliography: ("./bib/bias.bib")
%%% End:
